# Generated by Django 5.1.4 on 2026-01-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_processed',
            field=models.BooleanField(default=False),
        ),
    ]
