# Generated by Django 5.1.4 on 2026-01-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_checkout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='environment',
            field=models.CharField(choices=[('TEST', 'Test'), ('LIVE', 'Live')], default='TEST', max_length=10),
        ),
    ]
