# Generated by Django 5.1.4 on 2026-01-15 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchantapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(help_text='Individual or Registered Business', max_length=50)),
                ('business_address', models.TextField()),
                ('owner_full_name', models.CharField(max_length=255)),
                ('owner_date_of_birth', models.DateField()),
                ('document_type', models.CharField(choices=[('NIN', 'National ID'), ('PASSPORT', 'International Passport'), ('DRIVERS_LICENSE', "Driver's License")], max_length=30)),
                ('document_number', models.CharField(max_length=100)),
                ('document_image', models.ImageField(upload_to='kyc_documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='merchants.merchantprofile')),
            ],
        ),
    ]
