# Generated by Django 5.1.4 on 2026-01-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_alter_merchantprofile_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantapikey',
            name='secret_key',
            field=models.CharField(default='temporary-secret', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
