# Generated by Django 5.1.4 on 2026-01-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0005_merchantapikey_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
