# Generated by Django 5.1.4 on 2026-01-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0006_alter_merchantprofile_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
