# Generated by Django 5.1.4 on 2026-01-15 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0002_merchantapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('NGN', 'Naira'), ('USD', 'US Dollar'), ('USDT', 'Tether'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=10)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='merchants.merchantprofile')),
            ],
            options={
                'unique_together': {('merchant', 'currency')},
            },
        ),
    ]
